from pyChatGPT import ChatGPT

session_token = 'abc123'  # `__Secure-next-auth.session-token` cookie from https://chat.openai.com/chat
api1 = ChatGPT(session_token)  # auth with session token
api2 = ChatGPT(session_token, proxy='http://proxy.example.com:8080')  # specify proxy
api3 = ChatGPT(auth_type='google', email='example@gmail.com', password='password')  # auth with google login
api4 = ChatGPT(session_token, moderation=False)  # disable moderation
api5 = ChatGPT(session_token, window_size=(1024, 768))  # specify window size
api6 = ChatGPT(session_token, verbose=True)  # verbose mode (print debug messages)

# login with openai and solve simple reCAPTCHA automatically, but you should reCAPTCHA by yourself,
# it does not work on server without GUI.
api7 = ChatGPT(auth_type='openai', email='example@xxx.com', password='password', verbose=True)
# login with openai and solve simple reCAPTCHA automatically, while pass reCAPTCHA enterprise with 2captcha API,
# it works on server without GUI.
api8 = ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
               twocaptcha_apikey='2captcha_apikey',
               verbose=True)
# reuse cookies generated by successful login before login, if `login_cookies_path` does not exist, it will process
# logining  with `auth_type`, and save cookies to `login_cookies_path` only works when `auth_type` is `openai` or
# `google`
api9 = ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
               login_cookies_path='your_cookies_path',
               verbose=True)

resp = api1.send_message('Hello, world!')
print(resp['message'])

api1.reset_conversation()  # reset the conversation
api1.clear_conversations()  # clear all conversations
api1.refresh_chat_page()  # refresh the chat page